/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type CreatePlanUpdateFormInputValues = {
    userId?: string;
    PSProblemSolving?: boolean;
    PSSelfEsteem?: boolean;
    PSChoiceAutonomy?: boolean;
    PSSelfCare?: boolean;
    PSSelfAwareness?: boolean;
    PSCreativity?: boolean;
    CSForgiveness?: boolean;
    CSKindness?: boolean;
    CSGratitude?: boolean;
    CSPatience?: boolean;
    CSCourage?: boolean;
    CMSCopingChoice?: boolean;
    CMSResilience?: boolean;
    CMSSelfRegulation?: boolean;
    CMSOptimism?: boolean;
    COMSupportSystem?: boolean;
    COMSocialIntelligence?: boolean;
    COMCommunication?: boolean;
    COMFaithCommunity?: boolean;
    COMAccomplishments?: boolean;
    BRStableHousing?: boolean;
    BRQualityHealthcare?: boolean;
    BRProfessionalAccess?: boolean;
    BRInsuranceCoverage?: boolean;
    BRFinancialConstraints?: boolean;
    BREducationAttainment?: boolean;
    BRSocialStigma?: boolean;
    BRUnsupportiveCommunity?: boolean;
    BRNonexistentCommunity?: boolean;
    BRCommunityResources?: boolean;
    BRProfessionalTrust?: boolean;
    BRHealthcareSystemTrust?: boolean;
    BRCognitiveImpairments?: boolean;
    BRDependentCare?: boolean;
    BRTransportation?: boolean;
    BRTechnologyAccess?: boolean;
    BRLanguage?: boolean;
    BRHealthcareProcess?: boolean;
    BROther?: boolean;
    BRResponseNote?: string;
    TGBetrayal?: boolean;
    TGBoundaries?: boolean;
    TGDisorder?: boolean;
    TGPain?: boolean;
    TGRejection?: boolean;
    TGStress?: boolean;
    TGMemories?: boolean;
    TGUnjustTreatment?: boolean;
    TGUnpleasantConversations?: boolean;
    TGUnsafeEnvironments?: boolean;
    TGOther?: boolean;
    WSFlashbacks?: boolean;
    WSIncreasedAppetite?: boolean;
    WSDecreasedAppetite?: boolean;
    WSIntenseEmotions?: boolean;
    WSDisconnecting?: boolean;
    WSTime?: boolean;
    WSNegativeSelfTalk?: boolean;
    WSNeglectingSelfCare?: boolean;
    WSNightmares?: boolean;
    WSRecklessBehavior?: boolean;
    WSOther?: boolean;
};
export declare type CreatePlanUpdateFormValidationValues = {
    userId?: ValidationFunction<string>;
    PSProblemSolving?: ValidationFunction<boolean>;
    PSSelfEsteem?: ValidationFunction<boolean>;
    PSChoiceAutonomy?: ValidationFunction<boolean>;
    PSSelfCare?: ValidationFunction<boolean>;
    PSSelfAwareness?: ValidationFunction<boolean>;
    PSCreativity?: ValidationFunction<boolean>;
    CSForgiveness?: ValidationFunction<boolean>;
    CSKindness?: ValidationFunction<boolean>;
    CSGratitude?: ValidationFunction<boolean>;
    CSPatience?: ValidationFunction<boolean>;
    CSCourage?: ValidationFunction<boolean>;
    CMSCopingChoice?: ValidationFunction<boolean>;
    CMSResilience?: ValidationFunction<boolean>;
    CMSSelfRegulation?: ValidationFunction<boolean>;
    CMSOptimism?: ValidationFunction<boolean>;
    COMSupportSystem?: ValidationFunction<boolean>;
    COMSocialIntelligence?: ValidationFunction<boolean>;
    COMCommunication?: ValidationFunction<boolean>;
    COMFaithCommunity?: ValidationFunction<boolean>;
    COMAccomplishments?: ValidationFunction<boolean>;
    BRStableHousing?: ValidationFunction<boolean>;
    BRQualityHealthcare?: ValidationFunction<boolean>;
    BRProfessionalAccess?: ValidationFunction<boolean>;
    BRInsuranceCoverage?: ValidationFunction<boolean>;
    BRFinancialConstraints?: ValidationFunction<boolean>;
    BREducationAttainment?: ValidationFunction<boolean>;
    BRSocialStigma?: ValidationFunction<boolean>;
    BRUnsupportiveCommunity?: ValidationFunction<boolean>;
    BRNonexistentCommunity?: ValidationFunction<boolean>;
    BRCommunityResources?: ValidationFunction<boolean>;
    BRProfessionalTrust?: ValidationFunction<boolean>;
    BRHealthcareSystemTrust?: ValidationFunction<boolean>;
    BRCognitiveImpairments?: ValidationFunction<boolean>;
    BRDependentCare?: ValidationFunction<boolean>;
    BRTransportation?: ValidationFunction<boolean>;
    BRTechnologyAccess?: ValidationFunction<boolean>;
    BRLanguage?: ValidationFunction<boolean>;
    BRHealthcareProcess?: ValidationFunction<boolean>;
    BROther?: ValidationFunction<boolean>;
    BRResponseNote?: ValidationFunction<string>;
    TGBetrayal?: ValidationFunction<boolean>;
    TGBoundaries?: ValidationFunction<boolean>;
    TGDisorder?: ValidationFunction<boolean>;
    TGPain?: ValidationFunction<boolean>;
    TGRejection?: ValidationFunction<boolean>;
    TGStress?: ValidationFunction<boolean>;
    TGMemories?: ValidationFunction<boolean>;
    TGUnjustTreatment?: ValidationFunction<boolean>;
    TGUnpleasantConversations?: ValidationFunction<boolean>;
    TGUnsafeEnvironments?: ValidationFunction<boolean>;
    TGOther?: ValidationFunction<boolean>;
    WSFlashbacks?: ValidationFunction<boolean>;
    WSIncreasedAppetite?: ValidationFunction<boolean>;
    WSDecreasedAppetite?: ValidationFunction<boolean>;
    WSIntenseEmotions?: ValidationFunction<boolean>;
    WSDisconnecting?: ValidationFunction<boolean>;
    WSTime?: ValidationFunction<boolean>;
    WSNegativeSelfTalk?: ValidationFunction<boolean>;
    WSNeglectingSelfCare?: ValidationFunction<boolean>;
    WSNightmares?: ValidationFunction<boolean>;
    WSRecklessBehavior?: ValidationFunction<boolean>;
    WSOther?: ValidationFunction<boolean>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type CreatePlanUpdateFormOverridesProps = {
    CreatePlanUpdateFormGrid?: PrimitiveOverrideProps<GridProps>;
    userId?: PrimitiveOverrideProps<TextFieldProps>;
    PSProblemSolving?: PrimitiveOverrideProps<SwitchFieldProps>;
    PSSelfEsteem?: PrimitiveOverrideProps<SwitchFieldProps>;
    PSChoiceAutonomy?: PrimitiveOverrideProps<SwitchFieldProps>;
    PSSelfCare?: PrimitiveOverrideProps<SwitchFieldProps>;
    PSSelfAwareness?: PrimitiveOverrideProps<SwitchFieldProps>;
    PSCreativity?: PrimitiveOverrideProps<SwitchFieldProps>;
    CSForgiveness?: PrimitiveOverrideProps<SwitchFieldProps>;
    CSKindness?: PrimitiveOverrideProps<SwitchFieldProps>;
    CSGratitude?: PrimitiveOverrideProps<SwitchFieldProps>;
    CSPatience?: PrimitiveOverrideProps<SwitchFieldProps>;
    CSCourage?: PrimitiveOverrideProps<SwitchFieldProps>;
    CMSCopingChoice?: PrimitiveOverrideProps<SwitchFieldProps>;
    CMSResilience?: PrimitiveOverrideProps<SwitchFieldProps>;
    CMSSelfRegulation?: PrimitiveOverrideProps<SwitchFieldProps>;
    CMSOptimism?: PrimitiveOverrideProps<SwitchFieldProps>;
    COMSupportSystem?: PrimitiveOverrideProps<SwitchFieldProps>;
    COMSocialIntelligence?: PrimitiveOverrideProps<SwitchFieldProps>;
    COMCommunication?: PrimitiveOverrideProps<SwitchFieldProps>;
    COMFaithCommunity?: PrimitiveOverrideProps<SwitchFieldProps>;
    COMAccomplishments?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRStableHousing?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRQualityHealthcare?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRProfessionalAccess?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRInsuranceCoverage?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRFinancialConstraints?: PrimitiveOverrideProps<SwitchFieldProps>;
    BREducationAttainment?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRSocialStigma?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRUnsupportiveCommunity?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRNonexistentCommunity?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRCommunityResources?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRProfessionalTrust?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRHealthcareSystemTrust?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRCognitiveImpairments?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRDependentCare?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRTransportation?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRTechnologyAccess?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRLanguage?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRHealthcareProcess?: PrimitiveOverrideProps<SwitchFieldProps>;
    BROther?: PrimitiveOverrideProps<SwitchFieldProps>;
    BRResponseNote?: PrimitiveOverrideProps<TextFieldProps>;
    TGBetrayal?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGBoundaries?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGDisorder?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGPain?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGRejection?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGStress?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGMemories?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGUnjustTreatment?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGUnpleasantConversations?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGUnsafeEnvironments?: PrimitiveOverrideProps<SwitchFieldProps>;
    TGOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSFlashbacks?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSIncreasedAppetite?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSDecreasedAppetite?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSIntenseEmotions?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSDisconnecting?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSTime?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSNegativeSelfTalk?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSNeglectingSelfCare?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSNightmares?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSRecklessBehavior?: PrimitiveOverrideProps<SwitchFieldProps>;
    WSOther?: PrimitiveOverrideProps<SwitchFieldProps>;
} & EscapeHatchProps;
export declare type CreatePlanUpdateFormProps = React.PropsWithChildren<{
    overrides?: CreatePlanUpdateFormOverridesProps | undefined | null;
} & {
    id?: string;
    createPlan?: any;
    onSubmit?: (fields: CreatePlanUpdateFormInputValues) => CreatePlanUpdateFormInputValues;
    onSuccess?: (fields: CreatePlanUpdateFormInputValues) => void;
    onError?: (fields: CreatePlanUpdateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: CreatePlanUpdateFormInputValues) => CreatePlanUpdateFormInputValues;
    onValidate?: CreatePlanUpdateFormValidationValues;
} & React.CSSProperties>;
export default function CreatePlanUpdateForm(props: CreatePlanUpdateFormProps): React.ReactElement;
