/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://t7lr2ugphzbedefmsvd7m6xzhy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7tpjb4gicfbplemh2ftvujuzo4",
    "aws_cloud_logic_custom": [
        {
            "name": "emailapi",
            "endpoint": "https://toa4mtttr4.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:678d1ed7-67a3-4991-8e2e-c5c7a3967fe1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lIA2rW7R3",
    "aws_user_pools_web_client_id": "d6iotnkf181soijrbekhb4kd1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "wholistichealthapp1ff4b8b301944852a9bdb77c39f1e6e3e6-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
