/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateLogin = /* GraphQL */ `
  subscription OnCreateLogin($filter: ModelSubscriptionLoginFilterInput) {
    onCreateLogin(filter: $filter) {
      id
      Email
      Password
      LoginDate
      LoginTime
      ProfileType
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onUpdateLogin = /* GraphQL */ `
  subscription OnUpdateLogin($filter: ModelSubscriptionLoginFilterInput) {
    onUpdateLogin(filter: $filter) {
      id
      Email
      Password
      LoginDate
      LoginTime
      ProfileType
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onDeleteLogin = /* GraphQL */ `
  subscription OnDeleteLogin($filter: ModelSubscriptionLoginFilterInput) {
    onDeleteLogin(filter: $filter) {
      id
      Email
      Password
      LoginDate
      LoginTime
      ProfileType
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      __typename
    }
  }
`;
export const onCreateCreatePlan = /* GraphQL */ `
  subscription OnCreateCreatePlan(
    $filter: ModelSubscriptionCreatePlanFilterInput
    $owner: String
  ) {
    onCreateCreatePlan(filter: $filter, owner: $owner) {
      id
      userId
      PSProblemSolving
      PSSelfEsteem
      PSChoiceAutonomy
      PSSelfCare
      PSSelfAwareness
      PSCreativity
      CSForgiveness
      CSKindness
      CSGratitude
      CSPatience
      CSCourage
      CMSCopingChoice
      CMSResilience
      CMSSelfRegulation
      CMSOptimism
      COMSupportSystem
      COMSocialIntelligence
      COMCommunication
      COMFaithCommunity
      COMAccomplishments
      BRStableHousing
      BRQualityHealthcare
      BRProfessionalAccess
      BRInsuranceCoverage
      BRFinancialConstraints
      BREducationAttainment
      BRSocialStigma
      BRUnsupportiveCommunity
      BRNonexistentCommunity
      BRCommunityResources
      BRProfessionalTrust
      BRHealthcareSystemTrust
      BRCognitiveImpairments
      BRDependentCare
      BRTransportation
      BRTechnologyAccess
      BRLanguage
      BRHealthcareProcess
      BROther
      BRResponseNote
      TGBetrayal
      TGBoundaries
      TGDisorder
      TGPain
      TGRejection
      TGStress
      TGMemories
      TGUnjustTreatment
      TGUnpleasantConversations
      TGUnsafeEnvironments
      TGOther
      WSFlashbacks
      WSIncreasedAppetite
      WSDecreasedAppetite
      WSIntenseEmotions
      WSDisconnecting
      WSTime
      WSNegativeSelfTalk
      WSNeglectingSelfCare
      WSNightmares
      WSRecklessBehavior
      WSOther
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateCreatePlan = /* GraphQL */ `
  subscription OnUpdateCreatePlan(
    $filter: ModelSubscriptionCreatePlanFilterInput
    $owner: String
  ) {
    onUpdateCreatePlan(filter: $filter, owner: $owner) {
      id
      userId
      PSProblemSolving
      PSSelfEsteem
      PSChoiceAutonomy
      PSSelfCare
      PSSelfAwareness
      PSCreativity
      CSForgiveness
      CSKindness
      CSGratitude
      CSPatience
      CSCourage
      CMSCopingChoice
      CMSResilience
      CMSSelfRegulation
      CMSOptimism
      COMSupportSystem
      COMSocialIntelligence
      COMCommunication
      COMFaithCommunity
      COMAccomplishments
      BRStableHousing
      BRQualityHealthcare
      BRProfessionalAccess
      BRInsuranceCoverage
      BRFinancialConstraints
      BREducationAttainment
      BRSocialStigma
      BRUnsupportiveCommunity
      BRNonexistentCommunity
      BRCommunityResources
      BRProfessionalTrust
      BRHealthcareSystemTrust
      BRCognitiveImpairments
      BRDependentCare
      BRTransportation
      BRTechnologyAccess
      BRLanguage
      BRHealthcareProcess
      BROther
      BRResponseNote
      TGBetrayal
      TGBoundaries
      TGDisorder
      TGPain
      TGRejection
      TGStress
      TGMemories
      TGUnjustTreatment
      TGUnpleasantConversations
      TGUnsafeEnvironments
      TGOther
      WSFlashbacks
      WSIncreasedAppetite
      WSDecreasedAppetite
      WSIntenseEmotions
      WSDisconnecting
      WSTime
      WSNegativeSelfTalk
      WSNeglectingSelfCare
      WSNightmares
      WSRecklessBehavior
      WSOther
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteCreatePlan = /* GraphQL */ `
  subscription OnDeleteCreatePlan(
    $filter: ModelSubscriptionCreatePlanFilterInput
    $owner: String
  ) {
    onDeleteCreatePlan(filter: $filter, owner: $owner) {
      id
      userId
      PSProblemSolving
      PSSelfEsteem
      PSChoiceAutonomy
      PSSelfCare
      PSSelfAwareness
      PSCreativity
      CSForgiveness
      CSKindness
      CSGratitude
      CSPatience
      CSCourage
      CMSCopingChoice
      CMSResilience
      CMSSelfRegulation
      CMSOptimism
      COMSupportSystem
      COMSocialIntelligence
      COMCommunication
      COMFaithCommunity
      COMAccomplishments
      BRStableHousing
      BRQualityHealthcare
      BRProfessionalAccess
      BRInsuranceCoverage
      BRFinancialConstraints
      BREducationAttainment
      BRSocialStigma
      BRUnsupportiveCommunity
      BRNonexistentCommunity
      BRCommunityResources
      BRProfessionalTrust
      BRHealthcareSystemTrust
      BRCognitiveImpairments
      BRDependentCare
      BRTransportation
      BRTechnologyAccess
      BRLanguage
      BRHealthcareProcess
      BROther
      BRResponseNote
      TGBetrayal
      TGBoundaries
      TGDisorder
      TGPain
      TGRejection
      TGStress
      TGMemories
      TGUnjustTreatment
      TGUnpleasantConversations
      TGUnsafeEnvironments
      TGOther
      WSFlashbacks
      WSIncreasedAppetite
      WSDecreasedAppetite
      WSIntenseEmotions
      WSDisconnecting
      WSTime
      WSNegativeSelfTalk
      WSNeglectingSelfCare
      WSNightmares
      WSRecklessBehavior
      WSOther
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateGeneralInformation = /* GraphQL */ `
  subscription OnCreateGeneralInformation(
    $filter: ModelSubscriptionGeneralInformationFilterInput
    $owner: String
  ) {
    onCreateGeneralInformation(filter: $filter, owner: $owner) {
      id
      userId
      FirstName
      LastName
      Email
      ProfessionalRole
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      OrganizationAdministrator
      OrganizationEmployee
      Department
      Service
      ProgramsUnit
      TrackPlan {
        nextToken
        __typename
      }
      AssessmentAnswers {
        nextToken
        __typename
      }
      ProfileType
      Login {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateGeneralInformation = /* GraphQL */ `
  subscription OnUpdateGeneralInformation(
    $filter: ModelSubscriptionGeneralInformationFilterInput
    $owner: String
  ) {
    onUpdateGeneralInformation(filter: $filter, owner: $owner) {
      id
      userId
      FirstName
      LastName
      Email
      ProfessionalRole
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      OrganizationAdministrator
      OrganizationEmployee
      Department
      Service
      ProgramsUnit
      TrackPlan {
        nextToken
        __typename
      }
      AssessmentAnswers {
        nextToken
        __typename
      }
      ProfileType
      Login {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteGeneralInformation = /* GraphQL */ `
  subscription OnDeleteGeneralInformation(
    $filter: ModelSubscriptionGeneralInformationFilterInput
    $owner: String
  ) {
    onDeleteGeneralInformation(filter: $filter, owner: $owner) {
      id
      userId
      FirstName
      LastName
      Email
      ProfessionalRole
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      OrganizationAdministrator
      OrganizationEmployee
      Department
      Service
      ProgramsUnit
      TrackPlan {
        nextToken
        __typename
      }
      AssessmentAnswers {
        nextToken
        __typename
      }
      ProfileType
      Login {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateAssessmentAnswers = /* GraphQL */ `
  subscription OnCreateAssessmentAnswers(
    $filter: ModelSubscriptionAssessmentAnswersFilterInput
    $owner: String
  ) {
    onCreateAssessmentAnswers(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      TrackPlan {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      SDoHReligion
      SDoHDenomination
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateAssessmentAnswers = /* GraphQL */ `
  subscription OnUpdateAssessmentAnswers(
    $filter: ModelSubscriptionAssessmentAnswersFilterInput
    $owner: String
  ) {
    onUpdateAssessmentAnswers(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      TrackPlan {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      SDoHReligion
      SDoHDenomination
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteAssessmentAnswers = /* GraphQL */ `
  subscription OnDeleteAssessmentAnswers(
    $filter: ModelSubscriptionAssessmentAnswersFilterInput
    $owner: String
  ) {
    onDeleteAssessmentAnswers(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      TrackPlan {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      SDoHReligion
      SDoHDenomination
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateAssessmentScores = /* GraphQL */ `
  subscription OnCreateAssessmentScores(
    $filter: ModelSubscriptionAssessmentScoresFilterInput
    $owner: String
  ) {
    onCreateAssessmentScores(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      SDoHReligion
      SDoHDenomination
      TRScore
      CMScore
      MHScore
      PHScore
      SHScore
      OLScore
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateAssessmentScores = /* GraphQL */ `
  subscription OnUpdateAssessmentScores(
    $filter: ModelSubscriptionAssessmentScoresFilterInput
    $owner: String
  ) {
    onUpdateAssessmentScores(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      SDoHReligion
      SDoHDenomination
      TRScore
      CMScore
      MHScore
      PHScore
      SHScore
      OLScore
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteAssessmentScores = /* GraphQL */ `
  subscription OnDeleteAssessmentScores(
    $filter: ModelSubscriptionAssessmentScoresFilterInput
    $owner: String
  ) {
    onDeleteAssessmentScores(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      TRHurtfulNames
      TRNoNurturing
      TRHit
      TRNeedsNotMet
      TRForcedSex
      TRResponsible
      TRViolence
      TRSubstanceAbuse
      TRMentalIllness
      TRParentDivorce
      TRParentIncarcerated
      TRHomelessness
      TRBodyFunction
      TRNaturalDisaster
      TRDirectTerrorism
      TRIndirectTerrorism
      TRLovedOne
      TRBelief
      TRResponseProfessional
      TRResponseFamilyFriend
      TRResponseGod
      TRResponseNoOne
      TRNoTrauma
      CMAlcohol
      CMDrugs
      CMOvereating
      CMSmoking
      CMGaming
      CMShopping
      CMGambling
      CMSex
      CMPorn
      CMBlaming
      CMHurting
      CMDisengage
      CMArt
      CMMusic
      CMPoetry
      CMReading
      CMGroups
      CMCounseling
      CMVenting
      CMWriting
      CMSensory
      CMDancing
      CMExercising
      CMWalking
      CMChange
      CMAnalyze
      CMDaydream
      CMPositive
      MHDxPTSD
      MHDxDepression
      MHDxSUD
      MHDxOtherMental
      MHSleeplessness
      MHAlcoholUse
      MHAnxiety
      MHDepression
      MHDrugUse
      MHGrief
      MHGuilt
      MHIrritability
      MHStress
      MHRegret
      MHSuicidalThoughts
      MHLoneliness
      MHWorry
      PHDxInfertility
      PHDxCurableSTD
      PHDxIncurableSTD
      PHDxCancer
      PHDxDiabetes
      PHDxHighBlood
      PHDxHeartDisease
      PHDxIrritableBowel
      PHDxVitA
      PHDxVitB
      PHDxVitC
      PHDxVitD
      PHDxVitE
      PHDxVitK
      PHDxAutoimmune
      PHDxOtherPhysical
      PHVegeFruits
      PHBeanLentils
      PHGrainBreads
      PHDairy
      PHMeat
      PHFishSeafood
      PHSweets
      PHWater
      PHPhysicalActivity
      SHSpiritualDefine
      SHSpiritualIntegrate
      SHPrayer
      SHSpiritualActivity
      SHReadText
      SHAlignText
      SHCommunity
      OLHope
      OLPeace
      OLLearning
      OLJoy
      OLStable
      OLSafety
      OLKindness
      OLForgiveness
      OLPatience
      OLRelationships
      OLBoundaries
      OLEUnpleasant
      OLEPleasant
      OLEControl
      OLENumber
      SDoHAgeRange
      SDoHRace
      SDoHGeographicRegion
      SDoHEthnicity
      SDoHState
      SDoHZipCode
      SDoHMaritalStatus
      SDoHMilitaryStatus
      SDoHGender
      SDoHEducation
      SDoHJobStatus
      SDoHIncome
      SDoHHousingStatus
      SDoHHomeAsChild
      SDoHReligion
      SDoHDenomination
      TRScore
      CMScore
      MHScore
      PHScore
      SHScore
      OLScore
      isActive
      SHSkip
      ProAssessmentFinalizedReview1
      ProAssessmentFinalizedReviewDate1
      ProAssessmentFinalizedName1
      ProAssessmentFinalizedRole1
      ProAssessmentFinalizedReview2
      ProAssessmentFinalizedReviewDate2
      ProAssessmentFinalizedName2
      ProAssessmentFinalizedRole2
      ProAssessmentFinalizedReview3
      ProAssessmentFinalizedReviewDate3
      ProAssessmentFinalizedName3
      ProAssessmentFinalizedRole3
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateTrackPlan = /* GraphQL */ `
  subscription OnCreateTrackPlan(
    $filter: ModelSubscriptionTrackPlanFilterInput
    $owner: String
  ) {
    onCreateTrackPlan(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      ActionDomain
      ActionQuestion
      Action
      Frequency
      ActionNote
      Update1Points
      Update1Note
      Update1Date
      Update2Points
      Update2Note
      Update2Date
      Update3Points
      Update3Note
      Update3Date
      Update4Points
      Update4Note
      Update4Date
      Update5Points
      Update5Note
      Update5Date
      Update6Points
      Update6Note
      Update6Date
      Update7Points
      Update7Note
      Update7Date
      Update8Points
      Update8Note
      Update8Date
      Percentage
      Discontinued
      DiscontinuedDate
      Successful
      SuccessfulDate
      AssessmentAnswers {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateTrackPlan = /* GraphQL */ `
  subscription OnUpdateTrackPlan(
    $filter: ModelSubscriptionTrackPlanFilterInput
    $owner: String
  ) {
    onUpdateTrackPlan(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      ActionDomain
      ActionQuestion
      Action
      Frequency
      ActionNote
      Update1Points
      Update1Note
      Update1Date
      Update2Points
      Update2Note
      Update2Date
      Update3Points
      Update3Note
      Update3Date
      Update4Points
      Update4Note
      Update4Date
      Update5Points
      Update5Note
      Update5Date
      Update6Points
      Update6Note
      Update6Date
      Update7Points
      Update7Note
      Update7Date
      Update8Points
      Update8Note
      Update8Date
      Percentage
      Discontinued
      DiscontinuedDate
      Successful
      SuccessfulDate
      AssessmentAnswers {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteTrackPlan = /* GraphQL */ `
  subscription OnDeleteTrackPlan(
    $filter: ModelSubscriptionTrackPlanFilterInput
    $owner: String
  ) {
    onDeleteTrackPlan(filter: $filter, owner: $owner) {
      id
      userId
      CompletedDate
      CompletedTime
      ActionDomain
      ActionQuestion
      Action
      Frequency
      ActionNote
      Update1Points
      Update1Note
      Update1Date
      Update2Points
      Update2Note
      Update2Date
      Update3Points
      Update3Note
      Update3Date
      Update4Points
      Update4Note
      Update4Date
      Update5Points
      Update5Note
      Update5Date
      Update6Points
      Update6Note
      Update6Date
      Update7Points
      Update7Note
      Update7Date
      Update8Points
      Update8Note
      Update8Date
      Percentage
      Discontinued
      DiscontinuedDate
      Successful
      SuccessfulDate
      AssessmentAnswers {
        nextToken
        __typename
      }
      GeneralInformation {
        nextToken
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateConnectionRequest = /* GraphQL */ `
  subscription OnCreateConnectionRequest(
    $filter: ModelSubscriptionConnectionRequestFilterInput
    $owner: String
  ) {
    onCreateConnectionRequest(filter: $filter, owner: $owner) {
      id
      requesterId
      requesterFirstName
      requesterLastName
      requesterEmail
      targetEmail
      status
      direction
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateConnectionRequest = /* GraphQL */ `
  subscription OnUpdateConnectionRequest(
    $filter: ModelSubscriptionConnectionRequestFilterInput
    $owner: String
  ) {
    onUpdateConnectionRequest(filter: $filter, owner: $owner) {
      id
      requesterId
      requesterFirstName
      requesterLastName
      requesterEmail
      targetEmail
      status
      direction
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteConnectionRequest = /* GraphQL */ `
  subscription OnDeleteConnectionRequest(
    $filter: ModelSubscriptionConnectionRequestFilterInput
    $owner: String
  ) {
    onDeleteConnectionRequest(filter: $filter, owner: $owner) {
      id
      requesterId
      requesterFirstName
      requesterLastName
      requesterEmail
      targetEmail
      status
      direction
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateUserLink = /* GraphQL */ `
  subscription OnCreateUserLink(
    $filter: ModelSubscriptionUserLinkFilterInput
    $owner: String
  ) {
    onCreateUserLink(filter: $filter, owner: $owner) {
      id
      professionalId
      professionalEmail
      professionalFirstName
      professionalLastName
      clientId
      clientEmail
      clientFirstName
      clientLastName
      clientViewable
      subscriptionId
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateUserLink = /* GraphQL */ `
  subscription OnUpdateUserLink(
    $filter: ModelSubscriptionUserLinkFilterInput
    $owner: String
  ) {
    onUpdateUserLink(filter: $filter, owner: $owner) {
      id
      professionalId
      professionalEmail
      professionalFirstName
      professionalLastName
      clientId
      clientEmail
      clientFirstName
      clientLastName
      clientViewable
      subscriptionId
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteUserLink = /* GraphQL */ `
  subscription OnDeleteUserLink(
    $filter: ModelSubscriptionUserLinkFilterInput
    $owner: String
  ) {
    onDeleteUserLink(filter: $filter, owner: $owner) {
      id
      professionalId
      professionalEmail
      professionalFirstName
      professionalLastName
      clientId
      clientEmail
      clientFirstName
      clientLastName
      clientViewable
      subscriptionId
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateOrganizationInformation = /* GraphQL */ `
  subscription OnCreateOrganizationInformation(
    $filter: ModelSubscriptionOrganizationInformationFilterInput
    $owner: String
  ) {
    onCreateOrganizationInformation(filter: $filter, owner: $owner) {
      id
      userId
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      Departments
      ProgramsUnits
      Services
      clientsServed
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateOrganizationInformation = /* GraphQL */ `
  subscription OnUpdateOrganizationInformation(
    $filter: ModelSubscriptionOrganizationInformationFilterInput
    $owner: String
  ) {
    onUpdateOrganizationInformation(filter: $filter, owner: $owner) {
      id
      userId
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      Departments
      ProgramsUnits
      Services
      clientsServed
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteOrganizationInformation = /* GraphQL */ `
  subscription OnDeleteOrganizationInformation(
    $filter: ModelSubscriptionOrganizationInformationFilterInput
    $owner: String
  ) {
    onDeleteOrganizationInformation(filter: $filter, owner: $owner) {
      id
      userId
      BusinessName
      BusinessEIN
      BusinessCountry
      BusinessAddress
      BusinessCity
      BusinessState
      BusinessZipCode
      BusinessPhoneNumber
      BusinessWebsite
      Departments
      ProgramsUnits
      Services
      clientsServed
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateOrganizationCPs = /* GraphQL */ `
  subscription OnCreateOrganizationCPs(
    $filter: ModelSubscriptionOrganizationCPsFilterInput
    $owner: String
  ) {
    onCreateOrganizationCPs(filter: $filter, owner: $owner) {
      id
      OrganizationId
      OrganizationCPFirstName
      OrganizationCPLastName
      OrganizationCPEmail
      OrganizationCPRole
      primaryDepartment
      primaryProgramsUnit
      primaryService
      OrganizationAdministrator
      PrimaryOrganizationAdministrator
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateOrganizationCPs = /* GraphQL */ `
  subscription OnUpdateOrganizationCPs(
    $filter: ModelSubscriptionOrganizationCPsFilterInput
    $owner: String
  ) {
    onUpdateOrganizationCPs(filter: $filter, owner: $owner) {
      id
      OrganizationId
      OrganizationCPFirstName
      OrganizationCPLastName
      OrganizationCPEmail
      OrganizationCPRole
      primaryDepartment
      primaryProgramsUnit
      primaryService
      OrganizationAdministrator
      PrimaryOrganizationAdministrator
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteOrganizationCPs = /* GraphQL */ `
  subscription OnDeleteOrganizationCPs(
    $filter: ModelSubscriptionOrganizationCPsFilterInput
    $owner: String
  ) {
    onDeleteOrganizationCPs(filter: $filter, owner: $owner) {
      id
      OrganizationId
      OrganizationCPFirstName
      OrganizationCPLastName
      OrganizationCPEmail
      OrganizationCPRole
      primaryDepartment
      primaryProgramsUnit
      primaryService
      OrganizationAdministrator
      PrimaryOrganizationAdministrator
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateNotifications = /* GraphQL */ `
  subscription OnCreateNotifications(
    $filter: ModelSubscriptionNotificationsFilterInput
    $owner: String
  ) {
    onCreateNotifications(filter: $filter, owner: $owner) {
      id
      RecommedationResult
      RecommedationAction
      RecommedationActionFrequency
      RecommedationType
      RecommedationNote
      RecommendationDate
      SenderId
      SenderFirstName
      SenderLastName
      SenderEmail
      TargetEmail
      NotificationType
      StatusDate
      Status
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateNotifications = /* GraphQL */ `
  subscription OnUpdateNotifications(
    $filter: ModelSubscriptionNotificationsFilterInput
    $owner: String
  ) {
    onUpdateNotifications(filter: $filter, owner: $owner) {
      id
      RecommedationResult
      RecommedationAction
      RecommedationActionFrequency
      RecommedationType
      RecommedationNote
      RecommendationDate
      SenderId
      SenderFirstName
      SenderLastName
      SenderEmail
      TargetEmail
      NotificationType
      StatusDate
      Status
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteNotifications = /* GraphQL */ `
  subscription OnDeleteNotifications(
    $filter: ModelSubscriptionNotificationsFilterInput
    $owner: String
  ) {
    onDeleteNotifications(filter: $filter, owner: $owner) {
      id
      RecommedationResult
      RecommedationAction
      RecommedationActionFrequency
      RecommedationType
      RecommedationNote
      RecommendationDate
      SenderId
      SenderFirstName
      SenderLastName
      SenderEmail
      TargetEmail
      NotificationType
      StatusDate
      Status
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateUserPayments = /* GraphQL */ `
  subscription OnCreateUserPayments(
    $filter: ModelSubscriptionUserPaymentsFilterInput
    $owner: String
  ) {
    onCreateUserPayments(filter: $filter, owner: $owner) {
      id
      userId
      organizationId
      organizationName
      paymentType
      subscriptionId
      paymentStatus
      clientsProjected
      costPerClient
      couponCode
      couponPercent
      paidUntil
      paymentFor
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateUserPayments = /* GraphQL */ `
  subscription OnUpdateUserPayments(
    $filter: ModelSubscriptionUserPaymentsFilterInput
    $owner: String
  ) {
    onUpdateUserPayments(filter: $filter, owner: $owner) {
      id
      userId
      organizationId
      organizationName
      paymentType
      subscriptionId
      paymentStatus
      clientsProjected
      costPerClient
      couponCode
      couponPercent
      paidUntil
      paymentFor
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteUserPayments = /* GraphQL */ `
  subscription OnDeleteUserPayments(
    $filter: ModelSubscriptionUserPaymentsFilterInput
    $owner: String
  ) {
    onDeleteUserPayments(filter: $filter, owner: $owner) {
      id
      userId
      organizationId
      organizationName
      paymentType
      subscriptionId
      paymentStatus
      clientsProjected
      costPerClient
      couponCode
      couponPercent
      paidUntil
      paymentFor
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateCoupon = /* GraphQL */ `
  subscription OnCreateCoupon(
    $filter: ModelSubscriptionCouponFilterInput
    $owner: String
  ) {
    onCreateCoupon(filter: $filter, owner: $owner) {
      id
      type
      value
      isActive
      maxUses
      timesUsed
      expiresAt
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateCoupon = /* GraphQL */ `
  subscription OnUpdateCoupon(
    $filter: ModelSubscriptionCouponFilterInput
    $owner: String
  ) {
    onUpdateCoupon(filter: $filter, owner: $owner) {
      id
      type
      value
      isActive
      maxUses
      timesUsed
      expiresAt
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteCoupon = /* GraphQL */ `
  subscription OnDeleteCoupon(
    $filter: ModelSubscriptionCouponFilterInput
    $owner: String
  ) {
    onDeleteCoupon(filter: $filter, owner: $owner) {
      id
      type
      value
      isActive
      maxUses
      timesUsed
      expiresAt
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateProfessionalReviews = /* GraphQL */ `
  subscription OnCreateProfessionalReviews(
    $filter: ModelSubscriptionProfessionalReviewsFilterInput
    $owner: String
  ) {
    onCreateProfessionalReviews(filter: $filter, owner: $owner) {
      id
      ReviewedId
      ReviewType
      ProfessionalName
      ProfessionalRole
      ReviewDate
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateProfessionalReviews = /* GraphQL */ `
  subscription OnUpdateProfessionalReviews(
    $filter: ModelSubscriptionProfessionalReviewsFilterInput
    $owner: String
  ) {
    onUpdateProfessionalReviews(filter: $filter, owner: $owner) {
      id
      ReviewedId
      ReviewType
      ProfessionalName
      ProfessionalRole
      ReviewDate
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteProfessionalReviews = /* GraphQL */ `
  subscription OnDeleteProfessionalReviews(
    $filter: ModelSubscriptionProfessionalReviewsFilterInput
    $owner: String
  ) {
    onDeleteProfessionalReviews(filter: $filter, owner: $owner) {
      id
      ReviewedId
      ReviewType
      ProfessionalName
      ProfessionalRole
      ReviewDate
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateLoginGeneralInformation = /* GraphQL */ `
  subscription OnCreateLoginGeneralInformation(
    $filter: ModelSubscriptionLoginGeneralInformationFilterInput
    $owner: String
  ) {
    onCreateLoginGeneralInformation(filter: $filter, owner: $owner) {
      id
      loginId
      generalInformationId
      login {
        id
        Email
        Password
        LoginDate
        LoginTime
        ProfileType
        createdAt
        updatedAt
        __typename
      }
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateLoginGeneralInformation = /* GraphQL */ `
  subscription OnUpdateLoginGeneralInformation(
    $filter: ModelSubscriptionLoginGeneralInformationFilterInput
    $owner: String
  ) {
    onUpdateLoginGeneralInformation(filter: $filter, owner: $owner) {
      id
      loginId
      generalInformationId
      login {
        id
        Email
        Password
        LoginDate
        LoginTime
        ProfileType
        createdAt
        updatedAt
        __typename
      }
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteLoginGeneralInformation = /* GraphQL */ `
  subscription OnDeleteLoginGeneralInformation(
    $filter: ModelSubscriptionLoginGeneralInformationFilterInput
    $owner: String
  ) {
    onDeleteLoginGeneralInformation(filter: $filter, owner: $owner) {
      id
      loginId
      generalInformationId
      login {
        id
        Email
        Password
        LoginDate
        LoginTime
        ProfileType
        createdAt
        updatedAt
        __typename
      }
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateGeneralInformationTrackPlan = /* GraphQL */ `
  subscription OnCreateGeneralInformationTrackPlan(
    $filter: ModelSubscriptionGeneralInformationTrackPlanFilterInput
    $owner: String
  ) {
    onCreateGeneralInformationTrackPlan(filter: $filter, owner: $owner) {
      id
      generalInformationId
      trackPlanId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateGeneralInformationTrackPlan = /* GraphQL */ `
  subscription OnUpdateGeneralInformationTrackPlan(
    $filter: ModelSubscriptionGeneralInformationTrackPlanFilterInput
    $owner: String
  ) {
    onUpdateGeneralInformationTrackPlan(filter: $filter, owner: $owner) {
      id
      generalInformationId
      trackPlanId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteGeneralInformationTrackPlan = /* GraphQL */ `
  subscription OnDeleteGeneralInformationTrackPlan(
    $filter: ModelSubscriptionGeneralInformationTrackPlanFilterInput
    $owner: String
  ) {
    onDeleteGeneralInformationTrackPlan(filter: $filter, owner: $owner) {
      id
      generalInformationId
      trackPlanId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateGeneralInformationAssessmentAnswers = /* GraphQL */ `
  subscription OnCreateGeneralInformationAssessmentAnswers(
    $filter: ModelSubscriptionGeneralInformationAssessmentAnswersFilterInput
    $owner: String
  ) {
    onCreateGeneralInformationAssessmentAnswers(
      filter: $filter
      owner: $owner
    ) {
      id
      generalInformationId
      assessmentAnswersId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateGeneralInformationAssessmentAnswers = /* GraphQL */ `
  subscription OnUpdateGeneralInformationAssessmentAnswers(
    $filter: ModelSubscriptionGeneralInformationAssessmentAnswersFilterInput
    $owner: String
  ) {
    onUpdateGeneralInformationAssessmentAnswers(
      filter: $filter
      owner: $owner
    ) {
      id
      generalInformationId
      assessmentAnswersId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteGeneralInformationAssessmentAnswers = /* GraphQL */ `
  subscription OnDeleteGeneralInformationAssessmentAnswers(
    $filter: ModelSubscriptionGeneralInformationAssessmentAnswersFilterInput
    $owner: String
  ) {
    onDeleteGeneralInformationAssessmentAnswers(
      filter: $filter
      owner: $owner
    ) {
      id
      generalInformationId
      assessmentAnswersId
      generalInformation {
        id
        userId
        FirstName
        LastName
        Email
        ProfessionalRole
        BusinessName
        BusinessEIN
        BusinessCountry
        BusinessAddress
        BusinessCity
        BusinessState
        BusinessZipCode
        BusinessPhoneNumber
        BusinessWebsite
        OrganizationAdministrator
        OrganizationEmployee
        Department
        Service
        ProgramsUnit
        ProfileType
        createdAt
        updatedAt
        owner
        __typename
      }
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onCreateAssessmentAnswersTrackPlan = /* GraphQL */ `
  subscription OnCreateAssessmentAnswersTrackPlan(
    $filter: ModelSubscriptionAssessmentAnswersTrackPlanFilterInput
    $owner: String
  ) {
    onCreateAssessmentAnswersTrackPlan(filter: $filter, owner: $owner) {
      id
      assessmentAnswersId
      trackPlanId
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onUpdateAssessmentAnswersTrackPlan = /* GraphQL */ `
  subscription OnUpdateAssessmentAnswersTrackPlan(
    $filter: ModelSubscriptionAssessmentAnswersTrackPlanFilterInput
    $owner: String
  ) {
    onUpdateAssessmentAnswersTrackPlan(filter: $filter, owner: $owner) {
      id
      assessmentAnswersId
      trackPlanId
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
export const onDeleteAssessmentAnswersTrackPlan = /* GraphQL */ `
  subscription OnDeleteAssessmentAnswersTrackPlan(
    $filter: ModelSubscriptionAssessmentAnswersTrackPlanFilterInput
    $owner: String
  ) {
    onDeleteAssessmentAnswersTrackPlan(filter: $filter, owner: $owner) {
      id
      assessmentAnswersId
      trackPlanId
      assessmentAnswers {
        id
        userId
        CompletedDate
        CompletedTime
        TRHurtfulNames
        TRNoNurturing
        TRHit
        TRNeedsNotMet
        TRForcedSex
        TRResponsible
        TRViolence
        TRSubstanceAbuse
        TRMentalIllness
        TRParentDivorce
        TRParentIncarcerated
        TRHomelessness
        TRBodyFunction
        TRNaturalDisaster
        TRDirectTerrorism
        TRIndirectTerrorism
        TRLovedOne
        TRBelief
        TRResponseProfessional
        TRResponseFamilyFriend
        TRResponseGod
        TRResponseNoOne
        TRNoTrauma
        CMAlcohol
        CMDrugs
        CMOvereating
        CMSmoking
        CMGaming
        CMShopping
        CMGambling
        CMSex
        CMPorn
        CMBlaming
        CMHurting
        CMDisengage
        CMArt
        CMMusic
        CMPoetry
        CMReading
        CMGroups
        CMCounseling
        CMVenting
        CMWriting
        CMSensory
        CMDancing
        CMExercising
        CMWalking
        CMChange
        CMAnalyze
        CMDaydream
        CMPositive
        MHDxPTSD
        MHDxDepression
        MHDxSUD
        MHDxOtherMental
        MHSleeplessness
        MHAlcoholUse
        MHAnxiety
        MHDepression
        MHDrugUse
        MHGrief
        MHGuilt
        MHIrritability
        MHStress
        MHRegret
        MHSuicidalThoughts
        MHLoneliness
        MHWorry
        PHDxInfertility
        PHDxCurableSTD
        PHDxIncurableSTD
        PHDxCancer
        PHDxDiabetes
        PHDxHighBlood
        PHDxHeartDisease
        PHDxIrritableBowel
        PHDxVitA
        PHDxVitB
        PHDxVitC
        PHDxVitD
        PHDxVitE
        PHDxVitK
        PHDxAutoimmune
        PHDxOtherPhysical
        PHVegeFruits
        PHBeanLentils
        PHGrainBreads
        PHDairy
        PHMeat
        PHFishSeafood
        PHSweets
        PHWater
        PHPhysicalActivity
        SHSpiritualDefine
        SHSpiritualIntegrate
        SHPrayer
        SHSpiritualActivity
        SHReadText
        SHAlignText
        SHCommunity
        OLHope
        OLPeace
        OLLearning
        OLJoy
        OLStable
        OLSafety
        OLKindness
        OLForgiveness
        OLPatience
        OLRelationships
        OLBoundaries
        OLEUnpleasant
        OLEPleasant
        OLEControl
        OLENumber
        SDoHAgeRange
        SDoHRace
        SDoHGeographicRegion
        SDoHEthnicity
        SDoHState
        SDoHZipCode
        SDoHMaritalStatus
        SDoHMilitaryStatus
        SDoHGender
        SDoHEducation
        SDoHJobStatus
        SDoHIncome
        SDoHHousingStatus
        SDoHHomeAsChild
        SDoHReligion
        SDoHDenomination
        isActive
        SHSkip
        ProAssessmentFinalizedReview1
        ProAssessmentFinalizedReviewDate1
        ProAssessmentFinalizedName1
        ProAssessmentFinalizedRole1
        ProAssessmentFinalizedReview2
        ProAssessmentFinalizedReviewDate2
        ProAssessmentFinalizedName2
        ProAssessmentFinalizedRole2
        ProAssessmentFinalizedReview3
        ProAssessmentFinalizedReviewDate3
        ProAssessmentFinalizedName3
        ProAssessmentFinalizedRole3
        createdAt
        updatedAt
        owner
        __typename
      }
      trackPlan {
        id
        userId
        CompletedDate
        CompletedTime
        ActionDomain
        ActionQuestion
        Action
        Frequency
        ActionNote
        Update1Points
        Update1Note
        Update1Date
        Update2Points
        Update2Note
        Update2Date
        Update3Points
        Update3Note
        Update3Date
        Update4Points
        Update4Note
        Update4Date
        Update5Points
        Update5Note
        Update5Date
        Update6Points
        Update6Note
        Update6Date
        Update7Points
        Update7Note
        Update7Date
        Update8Points
        Update8Note
        Update8Date
        Percentage
        Discontinued
        DiscontinuedDate
        Successful
        SuccessfulDate
        createdAt
        updatedAt
        owner
        __typename
      }
      createdAt
      updatedAt
      owner
      __typename
    }
  }
`;
